
name: "Debug"
on:
  workflow_dispatch:

jobs:
  run-just:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-18.04 ]
    steps:
      - name: Print state
        run: |
          echo "Printing"
          echo ${{ runner.os }}
          echo ${{ matrix.os }}
