
name: "Debug"
on:
  workflow_dispatch:

jobs:
  run-just:
    runs-on: macos-latest
    steps:
      - name: Update pointer
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token {{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/pawelpasterz/flank/dispatches" -d '{"event_type":"date-pointer"}'
      - name: Just run zerio
        run: |
          echo $(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/pawelpasterz/flank/actions/workflows/debug.yml/runs?per_page=20&page=1")
      - name: Just run
        run: |
          echo $(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/pawelpasterz/flank/actions/workflows/date_pointer.yml/runs?per_page=20&page=1")
      - uses: actions/checkout@v2
      - run: |
          ./gradlew assemble
          java -jar ./flank-scripts/build/libs/flank-scripts.jar shell firebase checkForSdkUpdate \
          --github-token=${{ secrets.GITHUB_TOKEN }} \
          --zenhub-token=${{ secrets.ZENHUB_API_KEY }}
