
name: "Debug"
on:
  workflow_dispatch:

jobs:
  run-just:
    runs-on: macos-latest
    steps:
      - name: Print state
        run: |
          echo "Printing"
          echo ${{ env }}
          echo ${{ toJSON(env) }}
