name: Debug flow

on:
  workflow_dispatch:    # or manually

jobs:
  just_run:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
