name: IT cron

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 everyday
  workflow_dispatch:    # or manually

jobs:
  run_it_full_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: '${{ secrets.GITHUB_TOKEN }}'
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ubuntu-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ubuntu-gradle-
            
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: 'YYYY-MM-DD HH:mm'
          utcOffset: "+00:00"      

      - name: Gradle clean build
        uses: eskatos/gradle-command-action@v1
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.ref }}
        with:
          arguments: "clean test"

      - name: Check for opened issues
        if: failure()
        id: check-opened
        run: |
          resp=$(curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/pawelpasterz/flank/issues?creator=github-actions[bot]&state=open&labels=IT_Failed" | jq .)
          echo $resp
          if [ $resp = "[]" ]
          then
            echo "::set-output should_create=true"
          else
            echo "::set-output should_create=false"
          fi
          
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ steps.check-opened.outputs.should_create == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_DATE: ${{ steps.current-time.outputs.formattedTime }}
          RUN_ID: ${{ github.run_id }}
          BUILD_SCAN_URL: ${{ steps.build.outputs.build-scan-url }}
        with:
          filename: .github/ISSUE_TEMPLATE/it_failed_template.md
          
      
