name: ubuntu-workflow

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened ]
    branches:
      - '*'
    paths:
      - '**'
      - '!flank-scripts/**'
  issue_comment:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - uses: octokit/request-action@v2.x
        id: re_run
        with:
          route: GET /repos/pawelpasterz/flank/actions/runs/333473275/rerun
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: 'echo ${{ github.event_name }}'
      
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'Test trigger'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      
      - id: should_run
        run: 'echo "::set-output name=run::true"'
        if: steps.check.outputs.triggered == 'true' || github.event_name == 'push' || github.event_name == 'pull_request'
      
      - name: Display the java version
        run: java -version
        shell: bash

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle clean build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "clean build"
