name: ubuntu-workflow

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened ]
    branches:
      - '*'
    paths:
      - '**'
      - '!flank-scripts/**'
  pull_request_review_comment:
  issue_comment:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: octokit/request-action@v2.x
        id: re_run
        with:
          route: GET /repos/pawelpasterz/flank/actions/runs/333473275/rerun
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo ${{ toJson(github) }}
          
      - run: |
          cat ${{ github.event_path }}
        
      - run: 'echo ref ${{ github.ref }}'
        
      - run: 'echo event_name ${{ github.event_name }}'
      
      - name: Display the java version
        run: java -version
        shell: bash

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle clean build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "clean build"
